# Odysseus AgentOS — M5 COMPLETE Launch (all kill-switches + LangGraph)
$env:ODYSSEUS_PHASE_TRACKER = "on"
$env:ODYSSEUS_RRF_FUSION = "on"
$env:ODYSSEUS_MEM0 = "on"
$env:ODYSSEUS_MEILISEARCH = "on"
$env:ODYSSEUS_LANGFUSE = "on"
$env:ODYSSEUS_LANGGRAPH = "on"
$env:ODYSSEUS_LANGGRAPH_INTERRUPT = "on"
$env:ODYSSEUS_GOVERNANCE_ANCESTRY = "on"
$env:ODYSSEUS_AUTOEVAL = "on"
$env:ODYSSEUS_CHECKPOINT = "on"
$env:ODYSSEUS_UNIFIED_TOKENS = "on"
$env:ODYSSEUS_CODEBURN = "on"
$env:ODYSSEUS_AGENT_CATALOG = "on"
$env:ODYSSEUS_AGENT_PLANNER = "on"
$env:ODYSSEUS_AGENT_EXECUTOR = "on"
$env:ODYSSEUS_AGENT_VERIFIER = "on"
$env:ODYSSEUS_OBSIDIAN_MCP = "on"
$env:ODYSSEUS_GRAPHIFY = "on"
$env:ODYSSEUS_LIVE_ORCHESTRATION = "on"
$env:ODYSSEUS_MODEL_ROUTER = "on"
$env:ODYSSEUS_ZEN_FROM_ENDPOINT = "on"
$env:AUTH_ENABLED = "false"
$env:LOCALHOST_BYPASS = "true"
$env:ODYSSEUS_MEILI_HOST = "localhost"
$env:MEILI_HOST = "localhost"

Set-Location "C:\Users\ttmdu\Documents\GitHub\odysseusAgentOS"
python -m uvicorn app:app --host 127.0.0.1 --port 7000
